### ISSUE TITLE
Root domain static site

### ISSUE THREAD

**Issue by kaihendry** [aws-samples/aws-cdk-examples#151]
Similar to https://github.com/aws-samples/aws-cdk-examples/issues/102#issuecomment-549855252 but with no subdomains. 

I tried d85826645180871701f296c8937495b3d3a23a9d with cdk 1.15.0 (build bdbe3aa) and the error is **The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME)** like #102 iirc.

https://s.natalian.org/2019-11-06/fail.txt

**Comment by rhboyd** [comment]
Full disclosure: this probably won't be prioritized for this repository. This repo serves as examples for how similar constructs are created in various languages and there isn't much value to our users in adding incremental features for specific use-cases. Such examples would probably be better served in some kind of "quick-starts" focused repository that is meant to provide a fully-featured turn-key experience for a production-ready application. This repository is meant to be a teaching exercise and some of the examples here are intentionally designed so that they don't deploy or they ignore production best practices. It would be dangerous to mix such use-cases in a single repository as users would have trouble distinguishing between teaching examples and production examples.

**Comment by kaiz-io** [comment]
Closing Reopen if still issue.
