### ISSUE TITLE
.net cdk CfnQueueProps RedrivePolicy property

### ISSUE THREAD

**Issue by abaccin** [aws-samples/aws-cdk-examples#232]
### The Question
I am trying to set the RedrivePolicy of SQS using CfnQueueProps:

``` c#
var sqsQueue = Amazon.CDK.AWS.SQS.Queue.FromQueueArn(this,someId, someArn);
var dl = new DeadLetterQueue { MaxReceiveCount = 5, Queue = sqsQueue };
var queueProps = new CfnQueueProps
{
	VisibilityTimeout = TimeSpan.FromMinutes(5).TotalSeconds,
	QueueName = "myqueuename,
	MessageRetentionPeriod = TimeSpan.FromDays(14).TotalSeconds,
	RedrivePolicy = dl,
}; 
```
Result:

`Unhandled exception. Amazon.JSII.Runtime.JsiiException: Amazon.JSII.Runtime.JsiiException: Resolution error: Resolution error: Trying to resolve() a Construct at /Resources/`

Please note that the queue is being created in the current Stack but the dl is alredy in place.

### Environment

  - **CDK CLI Version:** 1.21.1 
  - **OS:** Windows 10
  - **Language:** c#

**Comment by NGL321** [comment]
Hey @abaccin, 

Sorry for the delay. My first suggestion is that rather than `CfnQueueProps` you should use `QueueProps`. The former is the raw Cloudformation resource from the L1 construct while the latter is the suggested props from the L2.

The JSII error strikes me as unrelated, but may have to do with different versions of the SQS library vs the core cdk library.

If you are still encountering this, check your Nuget package version numbers and let me know!


😸 😷

**Comment by sakopov** [comment]
> 
> 
> Hey @abaccin,
> 
> Sorry for the delay. My first suggestion is that rather than `CfnQueueProps` you should use `QueueProps`. The former is the raw Cloudformation resource from the L1 construct while the latter is the suggested props from the L2.
> 
> The JSII error strikes me as unrelated, but may have to do with different versions of the SQS library vs the core cdk library.
> 
> If you are still encountering this, check your Nuget package version numbers and let me know!
> 
> 😸 😷

I could be missing something but it doesn't look like `QueueProps` defines `RedrivePolicy` property. However, `CfnQueueProps` does.
