### ISSUE TITLE
static site example update suggestion

### ISSUE THREAD

**Issue by 007vasy** [aws-samples/aws-cdk-examples#394]
https://github.com/aws-samples/aws-cdk-examples/blob/b127242c30a70a13241f8a9d29006e7de7f36be1/typescript/static-site/index.ts#L32

`
   account: process.env.CDK_DEFAULT_ACCOUNT, 
   region: process.env.CDK_DEFAULT_REGION 
`
I made it work by adding this and calling it with: 
`
cdk deploy -c domain=<ADD_YOURS> -c subdomain=<ADD_YOURS>t -c CDK_DEFAULT_ACCOUNT=<ADD_YOURS> -c CDK_DEFAULT_REGION=<ADD_YOURS> --profile=<ADD_YOURS>
`

**Comment by ryparker** [comment]
Just updated the static-site example with basically this implementation: https://github.com/aws-samples/aws-cdk-examples/blob/2933fd4e86c1f3b08a0108ec62f576f745aff130/typescript/static-site/index.ts#L39

We left the region hardcoded because the ACM certificate for a global CloudFront distribution must be requested in us-east-1.

Closing this but please comment or feel free to reopen if you believe more should be done. 😄
