### ISSUE TITLE
(@aws-cdk/aws-elasticache): Examples requested

### ISSUE THREAD

**Issue by davidahopp** [aws-samples/aws-cdk-examples#534]
### General Information

Currently there are no examples building a CfnCacheCluster. During my building of my cluster, I ran into a poorly documented problem around assignment of the clusters subnet group. Basic examples could help solve this problem.

### Proposed Solution

An issue was created on the primary aws-cdk project that helped me solve my problem and provided an overall great example of creation of a cluster. I would recommend using this example as a good starting point: https://github.com/aws/aws-cdk/issues/4411

### Language

Typescript

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
I don't think this is something we'd want an example of in this repo - this repo is for examples of building real complicated infrastructure, rather than showing how to use a specific class (one that is autogenerated at that). When using CloudFormation resources, I would recommend checking out CloudFormation documentation
