### ISSUE TITLE
Example for Service Catalog with an EC2 Product Stack

### ISSUE THREAD

**Issue by mackalex** [aws-samples/aws-cdk-examples#595]
### General Information

This is a CDK example proposed by Service Catalog which will demonstrate the common Service Catalog usage pattern of creating a catalog of products with added governance.

The resources to be created by this example:
- Service Catalog Portfolio
- Service Catalog Product with multiple versions consisting of:
  - EC2 Instance w/ Amazon Linux AMI
  - VPC with public subnet
  - Security Group to allow SSH access to EC2 instance
  - IAM role for EC2 instance
- Service Catalog Launch Constraint on EC2 InstanceType
- IAM Role associated with Portfolio
- IAM Group associated with Portfolio
- Event Notification Constraint on Product

### Proposed Solution

A CDK sample written in both TypeScript and Python which demonstrates how to create a governed EC2 instance as a Service Catalog product. A new L2.5 feature of the Service Catalog CDK package known as ProductStack will be used to create a Service Catalog Product consisting of existing CDK constructs.

### Language

Typescript, Python

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by NGL321** [comment]
Hi @mackalex,

Thank you for checking in ahead of time. This sounds like a useful example to add to the repo. If I have a concern it is about the number of elements in a single example (despite them all being intricately linked) and whether it will end up being too large to be helpful. That said, this is something that can be resolved during a review of the example itself, so whenever you are ready to submit it, please request a review from me directly.

Additionally, since you are using a non-core construct, please make note in the README about implementing said construct.

😸 😷
