### ISSUE TITLE
(aws-cdk-examples): please update the static-site example to use the modern cloudfront Distribution API

### ISSUE THREAD

**Issue by lschierer** [aws-samples/aws-cdk-examples#609]
### General Information

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html#cloudfrontwebdistribution-api states that "The CloudFrontWebDistribution construct is the original construct written for working with CloudFront distributions. Users are encouraged to use the newer Distribution instead, as it has a simpler interface and receives new features faster." However, the example here uses the older API. I was looking for an example because I'm getting a lot of errors connecting CloudFront to an S3 bucket, but the mix of the older API here with the newer documentation doesn't help.

### Proposed Solution

Update the typescript/static-site example

### Language

Typescript

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
Hey, thank you for calling this out @lschierer 

I'll put this on my plate to do some point this week 🙂

**Comment by aisflat439** [comment]
@peterwoodworth when you take a look at this, can you also add in making static site work with the following

```
index.html
blog/index.html
```

The issue here that we're naming `StaticSite` and talking about hosting. Mostly, people would think that you can have a file at `/blog/index.html` and it wouldn't `403` because we're using the static site construct. however, this doesn't work without a cloudfront edge function.

You can see the process here (https://aws.amazon.com/blogs/compute/implementing-default-directory-indexes-in-amazon-s3-backed-amazon-cloudfront-origins-using-lambdaedge/) but it would be helpful if this was documented.

**Comment by peterwoodworth** [comment]
Hey, thanks for pinging me. I've actually since written a guide on [migrating](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront-readme.html#migrating-from-the-original-cloudfrontwebdistribution-to-the-newer-distribution-construct) between these constructs. I don't think I'll have time to work on this myself in the near future, but I'll be happy to take a look at a PR if someone wants to try to follow this migration guide for the existing example?

**Comment by its-mirus-lu** [comment]
@peterwoodworth I'd be able to take a look this weekend

**Comment by peterwoodworth** [comment]
Great, ping me if you run into any issues / when you're ready for a review

**Comment by its-mirus-lu** [comment]
@peterwoodworth that migration document was really easy to follow.  The PR is here: https://github.com/aws-samples/aws-cdk-examples/pull/624 have a look when you have a moment.

**Comment by blitzd** [comment]
@its-mirus-lu @peterwoodworth is there a specific version of CDK v2 required to use the new example? I'm on 2.15.0. I am trying to implement a static site based off of the example and running into the following error on deploy:

```
2:14:45 PM | CREATE_FAILED        | AWS::CloudFront::Distribution                   | viewersitedistributionDD520082
Properties validation failed for resource viewersitedistributionDD520082 with message:
#: extraneous key [MinimumProtocolVersion] is not permitted
#: extraneous key [ViewerCertificate] is not permitted
```

**Comment by peterwoodworth** [comment]
Thanks for calling this out @blitzd. I thought I was checking the output of the new branch when I was actually looking at the output of the old API. My mistake, I'll get it fixed up

**Comment by its-mirus-lu** [comment]
@peterwoodworth I found the error in my previous commit. I'll be raising a PR to address this issue today.

**Comment by peterwoodworth** [comment]
@its-mirus-lu thank you, this fell completely off my radar!

**Comment by its-mirus-lu** [comment]
`"StaticSiteSiteDistributionE3AF6299": {
      "Type": "AWS::CloudFront::Distribution",
      "Properties": {
        "DistributionConfig": {
          "Aliases": [
            ...
          ],
          "DefaultCacheBehavior": {
            "AllowedMethods": [
              "GET",
              "HEAD",
              "OPTIONS"
            ],
            ...
          "Origins": [
            ...
          ],
          "ViewerCertificate": {
            "AcmCertificateArn": {
              "Fn::GetAtt": [
                "StaticSiteSiteCertificateCertificateRequestorResourceB92D481B",
                "Arn"
              ]
            },
            "MinimumProtocolVersion": "TLSv1.2_2021",
            "SslSupportMethod": "sni-only"
          }
        },
        "ViewerCertificate": {
          "MinimumProtocolVersion": "TLS_V1_1_2016",
          "SslSupportMethod": "sni-only"
        }
      },
    },`

From my initial commit, the MinimumProtocolVersion and SslSupportMethod attributes were being placed in the high-level Distribution resource when it should be placed within the DistributionConfig property of the resource.

So from the code block where we use addPropertyOverride, this:

`cfnDistribution.addPropertyOverride('MinimumProtocolVersion', 'TLS_V1_1_2016')
cfnDistribution.addPropertyOverride('ViewerCertificate.SslSupportMethod', 'sni-only')`

becomes this:

`cfnDistribution.addPropertyOverride('DistributionConfig.ViewerCertificate.MinimumProtocolVersion', 'TLSv1.1_2016')
cfnDistribution.addPropertyOverride('DistributionConfig.ViewerCertificate.SslSupportMethod', 'sni-only')`

**Comment by its-mirus-lu** [comment]
@aisflat439 
> ```
> index.html
> blog/index.html
> ```
> 
> The issue here that we're naming `StaticSite` and talking about hosting. Mostly, people would think that you can have a file at `/blog/index.html` and it wouldn't `403` because we're using the static site construct. however, this doesn't work without a cloudfront edge function.
> 

The 403 errors are actually because the s3 bucket in the original example was setup with static website hosting -- this causes a situation in the S3Origin construct that doesn't attach an OAI. In my latest PR, I've disabled static hosting on s3 and so the distribution origin now properly configures an OAI to access all items in the bucket. Keep an eye on PR #632 -- or you can give it a shot pre merge if you want... I just tried adding /blog/index.html to the host bucket and was able to navigate by adding /blog/index.html to the path in my web browser without any errors (I didn't need an edge function either).
