### ISSUE TITLE
Error for Static site

### ISSUE THREAD

**Issue by sagarkukrejagit** [aws-samples/aws-cdk-examples#618]
Hi Team,

I am getting an error saying [Error at /MyStaticSite/StaticSite] Found zones: [] for dns:mystaticsite.com, privateZone:undefined, vpcId:undefined, but wanted exactly 1 zone
Found errors while i do cdk synth 

I have created a private hosted zone named mystaticsite.com in my AWS account and have linked the same in the code

Kindly look into it and guide me on the same.

Thank You.

Regards,
Sagar

**Comment by brian-stoker** [comment]
samesies..

**Comment by PavanMudigondaTR** [comment]
same error here

**Comment by gkfirst8** [comment]
Still happening. Any hints as to how this can be fixed? Looks like route53.HostedZone.fromLookup does get the zone but it seems to be incompatible with the zone needed for route53.ARecord.

**Comment by narcisghe** [comment]
in my case the issue was that i was using a domain name that was incorrect.

`    const hostedZone = route53.HostedZone.fromLookup(this, buildConfig.Parameters.AWS_HOSTED_ZONE_ID, { domainName: buildConfig.Parameters.AWS_DOMAIN_NAME });
`

The domain name i had to use was something like _link.something.com_ but i defined it as _api.link.something.com_

**Comment by kaiz-io** [comment]
To confirm this is the [typescript/static-site](https://github.com/aws-samples/aws-cdk-examples/tree/main/typescript/static-site) example?
