### ISSUE TITLE
Expand CDK Go Samples

### ISSUE THREAD

**Issue by yaseenyounus** [aws-samples/aws-cdk-examples#811]
### Describe the feature

When reviewing the AWS CDK Go samples, I noticed there weren't many present. Hopefully this issue will help drive adoption for using Go with CDK through clear samples. 

### Use Case

The goal of this issue if to increase the number of samples for Go to assist those who may be new to either Go or CDK.

### Proposed Solution

I can assist in creating new CDK Go samples as I have experience with both.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Go

**Comment by peterwoodworth** [comment]
Hey @yaseenyounus, thanks for helping us to improve this resource.

Your PR is being reviewed by another team member, but I just wanted to let you know that [there have been a number of Go examples](https://github.com/aws-samples/aws-cdk-examples/tree/master/go) which have recently been added since this was created, just in case you were interested 🙂

**Comment by yaseenyounus** [comment]
> Hey @yaseenyounus, thanks for helping us to improve this resource.
> 
> Your PR is being reviewed by another team member, but I just wanted to let you know that [there have been a number of Go examples](https://github.com/aws-samples/aws-cdk-examples/tree/master/go) which have recently been added since this was created, just in case you were interested 🙂

Glad to hear it! I have a couple more CDK Go sample ideas that I'll be writing up soon! Happy to help!
